### ISSUE TITLE
Interesting work! Add paper title 'Learned Legendre Predictive State Estimator for Control'.

### ISSUE THREAD

**Issue by 943fansi** [p3jawors/masters_thesis#1]

**Comment by p3jawors** [comment]
Thanks! Just curious, how did you come across my work? I've updated the README and install instructions. I still need to test things out and add instructions for running scripts.

Cheers

**Comment by 943fansi** [comment]
@p3jawors  Only because of Legendre's memory unit, I searched for relevant information on the Internet and found your paper, which was well written. There was an additional GitHub link, so the next thing happened.

Cheers

**Comment by p3jawors** [comment]
Thanks for the kind words
